image: php:7.2

before_script:
  - echo "Before script"
  - echo "Test echo"
#  - ls
  - mkdir /var/www/html/myvirtualshop
  - cd /var/www/html/myvirtualshop #your project path
building:
  stage: build
  script:
    - git reset --hard
    - git pull origin master
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R ubuntu /var/www/html/myvirtualshop/
    - find /var/www/html/myvirtualshop -type f -exec chmod 664 {} \;
    - find /var/www/html/myvirtualshop -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
#testing:
#  stage: test
#  script:
# - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
#   - php artisan queue:restart #if you use queue
